import { LessonPlan } from "../../types";

// Defines the result of a validation check.
export interface ValidationResult {
    isValid: boolean;
    errors: string[];
    sanitizedPlan?: LessonPlan;
}

// Defines the set of rules to check against.
const RULES = {
    REQUIRED_SCREEN_COUNT: 17,
};

/**
 * Validates and sanitizes a LessonPlan object generated by the AI.
 * It checks for structural integrity and adherence to core rules.
 *
 * @param plan The raw LessonPlan object from the AI.
 * @returns A ValidationResult object.
 */
export const validateLessonPlan = (plan: LessonPlan): ValidationResult => {
    const errors: string[] = [];

    // 1. Check for the existence of screens
    if (!plan.screens || !Array.isArray(plan.screens)) {
        return {
            isValid: false,
            errors: ["Lesson plan is missing 'screens' array."],
        };
    }

    // 2. Check for the exact number of screens
    if (plan.screens.length !== RULES.REQUIRED_SCREEN_COUNT) {
        errors.push(
            `Screen count is ${plan.screens.length}, but must be ${RULES.REQUIRED_SCREEN_COUNT}.`
        );
    }

    const sanitizedScreens = plan.screens.map((screen, index) => {
        // 3. Check for multiple interactive widgets on a single screen
        const interactiveTypes = ['quiz', 'parsons', 'fill-in', 'code-editor', 'steps-list'];
        let interactiveCount = 0;

        if (screen.widgets && Array.isArray(screen.widgets)) {
            screen.widgets.forEach(w => {
                if (w.type === 'flipcard' && w.flipcard?.mode === 'assessment') {
                    interactiveCount++;
                }
                if (interactiveTypes.includes(w.type)) {
                    interactiveCount++;
                }
            });
        }


        if (interactiveCount > 1) {
            errors.push(
                `Screen ${index + 1} has ${interactiveCount} interactive widgets, but only 1 is allowed.`
            );
        }

        return screen;
    });

    const isValid = errors.length === 0;

    return {
        isValid,
        errors,
        sanitizedPlan: isValid ? { ...plan, screens: sanitizedScreens } : undefined,
    };
};